name: Unit testing
on:
  pull_request:
    branches: [ main ]

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Use Node 20.9.0
      uses: actions/setup-node@v3
      with:
        node-version: '20.9.0'
    - name: npm install
      run: npm i
    - name: Unit testing
      run: npm test
    - name: E2e testing
      run: npm run e2e:tests